CREATE TABLE SCHEDULE_TBL(
SCHEDULEID VARCHAR2(8) PRIMARY KEY,
SOURCE VARCHAR2(30) NOT NULL,
DESTINATION VARCHAR2(30) NOT NULL,
STARTTIME VARCHAR2(5),
ARRIVALTIME VARCHAR2(5)
);
CREATE SEQUENCE SCHEDULE_SEQ START WITH 1000 INCREMENT BY 1 MAXVALUE 9999 MINVALUE 1000;